#!/bin/bash
git status

read -p "Are you sure you want to add&push all of this? [y/N] " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
echo ""

read -p "Commit message: " -r 

git add .
git commit -m "$REPLY"
git push
