#!/bin/bash
# 
# <<.bash_rc >>
# if [ -d "/opt/scripts" ] ; then
#   PATH="$PATH:/opt/scripts"
# fi

COMMAND=$1
VPN_CONFIG="Home"

case $COMMAND in
"up")
  wg-quick up $VPN_CONFIG
  ;;
"down")
  wg-quick down $VPN_CONFIG
  ;;
*)
  ip a show $VPN_CONFIG > /dev/null
  IS_ON=$?
  if [ ${IS_ON} -eq 1 ]; then
    echo "VPN is OFF - Starting..."
    wg-quick up $VPN_CONFIG
  fi
  if [ ${IS_ON} -eq 0 ]; then
    echo "VPN is ON - Disconnecting"
    wg-quick down $VPN_CONFIG
  fi
  ;;
"help")
  echo "USAGE:"
  echo "  vpn up (= wg-quick up $CONFIG)"
  echo "  vpn down (= wg-quick down $CONFIG)"
  echo "  vpn (toggle up/down)"
esac
